app = "zihaddhorm12"
primary_region = "sin"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  min_machines_running = 1

[[vm]]
  memory_mb = 256
  cpu_kind = "shared"
  cpus = 1
